version: '3'

services:
  test:
    image: todotests
    environment:
    - FRONT_HOST=todofront
    depends_on:
    - todoback
    - todofront
  todofront:
    image: todofrontend
    ports:
    - "3000:3000"
    environment: 
    - REACT_APP_HOST=todoback
  todoback:
    image: todobackend
    ports:
      -"3001:3001"


  
